/**
 * Server-only token auth. Kept out of the shared data core (database.ts) because
 * it uses node:crypto, which must not end up in the app's sql.js bundle.
 *
 * Model: one token per alias, generated by an admin (scripts/gen-token.js) and
 * stored HASHED. Requests carry `X-Alias` + `X-Auth-Token` headers. Reads (GET)
 * are open; writes require a valid token (enforced in middleware). So: no token
 * → read-only, valid token → full capability.
 */
import { createHash, timingSafeEqual } from 'node:crypto';
import type { SqlDriver } from './db/driver';

export function normalizeAlias(value: unknown): string {
  return typeof value === 'string' ? value.trim().slice(0, 128) : '';
}

export function hashToken(token: string): string {
  return createHash('sha256').update(token, 'utf8').digest('hex');
}

/** Create the token table (server-only; the app never validates tokens). */
export function ensureAuthSchema(driver: SqlDriver): void {
  driver.exec(`
    CREATE TABLE IF NOT EXISTS alias_tokens (
      alias      TEXT PRIMARY KEY,
      token_hash TEXT NOT NULL,
      created_at INTEGER NOT NULL
    )
  `);
}

export function setToken(driver: SqlDriver, alias: string, token: string): void {
  driver
    .prepare('INSERT OR REPLACE INTO alias_tokens (alias, token_hash, created_at) VALUES (?, ?, ?)')
    .run(normalizeAlias(alias), hashToken(token), Date.now());
}

/** Constant-time check that `token` matches the stored hash for `alias`. */
export function validateToken(driver: SqlDriver, alias: string, token: string): boolean {
  const a = normalizeAlias(alias);
  if (!a || !token) return false;
  const row = driver.prepare('SELECT token_hash FROM alias_tokens WHERE alias = ?').get(a) as
    | { token_hash: string }
    | undefined;
  if (!row) return false;
  const stored = Buffer.from(row.token_hash, 'hex');
  const given = Buffer.from(hashToken(token), 'hex');
  return stored.length === given.length && timingSafeEqual(stored, given);
}
